import type { Metadata } from "next"
import { getTheme } from "@/server/theme/theme"
import "./globals.css"
import { ThemeType } from "@/utils/types"

const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app" }


export default async function RootLayout({ children }: { children: Readonly<React.ReactNode> }) {
	const theme: ThemeType = await getTheme()
	return (
		<html lang="en" className={theme} suppressHydrationWarning>
			{children}
		</html>
	)
}
